#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
::#alpha::α
::#Alpha::𝒜
::#beta::β
::#Beta::
::#C::ℂ
::#cdot::·
::#congruent::≡
::#delta::δ
::#Delta::Δ
::#empty::∅
::#epsilon::ε
::#formula::𝒜
::#inf::∞
::#infty::∞
::#int::∫
::#Z::ℤ
::#iff::⇔
::#in::∈
::#iota::ι
::#la::←
::#lambda::λ
::#Lambda::Λ
::#loge::≡
::#leq::≤
::#N::ℕ
::#not::¬
::#null::∅
::#model::⊨
::#mu::μ
::#omega::ω
::#Omega::Ω
::#or::∨
::#phi::φ
::#Phi::Φ
::#Pi::𝝥
::#psi::ψ
::#Psi::Ψ
::#pset::𝓟
::#poset::≼
::#R::ℝ
::#ra::→
::#rightarrow::→
::#sigma::σ
::#Sigma::Σ
::#subseteq::⊆
::#subset::⊂
::#theta::θ
::#Theta::Θ